name: test

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Go 1.20.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install additional go tools
        run: |
          go get .
        shell: bash

      - name: Build
        run: go build
        shell: bash

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Test
        run: go test -v ./...
        shell: bash

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Go 1.20.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Fill releaser configuration
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "___SMTP_FROM___"
          replace: "${{ secrets.SMTP_FROM }}"
          regex: false
          include: ".goreleaser.yaml"

      - name: Fill releaser configuration
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "___SMTP_TARGET_0___"
          replace: "${{ secrets.SMTP_TARGET_0 }}"
          regex: false
          include: ".goreleaser.yaml"

      - name: Fill releaser configuration
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "___SMTP_TARGET_1___"
          replace: "${{ secrets.SMTP_TARGET_1 }}"
          regex: false
          include: ".goreleaser.yaml"

      - name: Fill releaser configuration
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "___SMTP_TARGET_2___"
          replace: "${{ secrets.SMTP_TARGET_2 }}"
          regex: false
          include: ".goreleaser.yaml"

      - name: Fill releaser configuration
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "___SMTP_TARGET_3___"
          replace: "${{ secrets.SMTP_TARGET_3 }}"
          regex: false
          include: ".goreleaser.yaml"

      - name: Fill env configuration with Sentry DSN
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "___SENTRY_DSN___"
          replace: "${{ secrets.SENTRY_DSN }}"
          regex: false
          include: "config/**.go"

      - name: Fill env configuration with Sentry env
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "___ENV___"
          replace: "${{ secrets.ENV }}"
          regex: false
          include: "config/**.go"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
