name: test

on:
  push:
    branches:
      - 'main'
      - 'releases/v*'
  pull_request:
    branches:
      - 'main'
      - 'releases/v*'

jobs:
  check:
    name: Build, Test, Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Go 1.17.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Install additional go tools
        run: |
          go get .
        shell: bash

      - name: Test
        run: go test -v ./...
        shell: bash